const properties=[
{id:'AN001',title:'Casa contemporânea com piscina',type:'Casa',purpose:'Comprar',district:'Centro',city:'Alagoinhas',price:890000,beds:3,suites:2,baths:4,parking:2,area:240,image:'hero.jpg',lat:-12.135,lng:-38.419,features:['Piscina','Área gourmet','Jardim','Varanda'],description:'Uma proposta de casa contemporânea com ambientes integrados, área de lazer e espaços amplos para viver com conforto. Cadastro ilustrativo para demonstrar a experiência de navegação.'},
{id:'AN002',title:'Casa com espaço para viver',type:'Casa',purpose:'Comprar',district:'Alagoinhas Velha',city:'Alagoinhas',price:560000,beds:3,suites:1,baths:2,parking:2,area:185,image:'house.jpg',lat:-12.116,lng:-38.409,features:['Quintal','Piscina','Sala integrada','Área de serviço'],description:'Ambientes acolhedores e uma área externa para aproveitar os dias em família. Imóvel demonstrativo; dados e fotografias não representam uma oferta real.'},
{id:'AN003',title:'Apartamento cheio de luz',type:'Apartamento',purpose:'Comprar',district:'Jardim Petrolar',city:'Alagoinhas',price:285000,beds:2,suites:1,baths:2,parking:1,area:78,image:'interior.jpg',lat:-12.148,lng:-38.402,features:['Sala de estar','Varanda','Cozinha integrada','Área de serviço'],description:'Um apartamento pensado para uma rotina prática, com sala iluminada e espaços integrados. Exemplo de apresentação, sem disponibilidade comercial confirmada.'},
{id:'AN004',title:'Apartamento para um novo começo',type:'Apartamento',purpose:'Alugar',district:'Centro',city:'Alagoinhas',price:1800,beds:2,suites:0,baths:1,parking:1,area:65,image:'interior.jpg',lat:-12.129,lng:-38.424,features:['Iluminação natural','Sala integrada','Cozinha','Área de serviço'],description:'Exemplo demonstrativo de imóvel para locação. Consulte André para conhecer opções reais, condições e disponibilidade.'}];
const $=s=>document.querySelector(s);const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});let favorites=[];try{favorites=JSON.parse(localStorage.getItem('an-favorites')||'[]');if(!Array.isArray(favorites))favorites=[]}catch{}let purpose='Comprar',onlyFavorites=false,map,markers,currentProperty,galleryIndex=0;const photos=p=>[p.image,...['hero.jpg','house.jpg','interior.jpg'].filter(x=>x!==p.image)];
function wa(message){return 'https://wa.me/5575999959930?text='+encodeURIComponent(message)}
function wireWA(){document.querySelectorAll('[data-wa]').forEach(a=>{a.href=wa(a.dataset.wa);a.target='_blank';a.rel='noopener'})}wireWA();
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];try{localStorage.setItem('an-favorites',JSON.stringify(favorites))}catch{}render();if(currentProperty)renderDetail(currentProperty,false)}
function filtered(){return properties.filter(p=>(onlyFavorites?favorites.includes(p.id):p.purpose===purpose)&&(!$('#type').value||p.type===$('#type').value)&&(!$('#city').value||p.city===$('#city').value)&&(!$('#district').value||p.district===$('#district').value)&&(!$('#price').value||p.price<=Number($('#price').value))&&(!$('#code').value||p.id.toLowerCase().includes($('#code').value.trim().toLowerCase())))}
function render(){const list=filtered();$('#fav-count').textContent=favorites.length;$('#cards').innerHTML=list.length?list.map(p=>`<article class="card"><div class="card-photo"><a href="#imovel/${p.id}" aria-label="Ver ${p.title}"><img src="${p.image}" alt="${p.title}, fotografia ilustrativa" loading="lazy" width="600" height="400"></a><span class="property-tag">${p.purpose==='Alugar'?'PARA ALUGAR':'À VENDA'} · DEMONSTRAÇÃO</span><button class="fav ${favorites.includes(p.id)?'selected':''}" data-fav="${p.id}" aria-label="${favorites.includes(p.id)?'Remover dos':'Adicionar aos'} favoritos" aria-pressed="${favorites.includes(p.id)}">${favorites.includes(p.id)?'♥':'♡'}</button></div><div class="card-body"><span class="card-label">${p.type} · ${p.id}</span><h3><a href="#imovel/${p.id}">${p.title}</a></h3><div class="location">⌖ ${p.district} — ${p.city}/BA</div><div class="amenities"><span>▱ ${p.beds} quartos</span><span>♧ ${p.baths} banheiros</span><span>▣ ${p.parking} vagas</span><span>⌑ ${p.area} m²</span></div><div class="card-price"><strong>${money(p.price)}${p.purpose==='Alugar'?'<small>/mês</small>':''}</strong><a href="#imovel/${p.id}">Ver imóvel ↗</a></div></div></article>`).join(''):'<div class="empty-state"><h3>Nenhum imóvel encontrado.</h3><p>Experimente outros filtros ou fale com André para encontrar seu imóvel.</p><a class="btn primary" href="'+wa('Olá André, não encontrei o imóvel que procuro. Pode me ajudar?')+'" target="_blank" rel="noopener">Falar com André ↗</a></div>';$('#result-status').textContent=list.length+' '+(list.length===1?'imóvel demonstrativo encontrado':'imóveis demonstrativos encontrados');document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=()=>toggleFavorite(b.dataset.fav));updateMarkers(list)}
document.querySelectorAll('[data-purpose]').forEach(b=>b.onclick=()=>{purpose=b.dataset.purpose;document.querySelectorAll('[data-purpose]').forEach(x=>x.classList.toggle('active',x===b));onlyFavorites=false;$('#favorite-filter').classList.remove('active');render()});
document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{$('#type').value=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('active',x===b));render()});
$('#search-form').onsubmit=e=>{e.preventDefault();document.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('active',x.dataset.category===$('#type').value));render();$('#imoveis').scrollIntoView({behavior:'smooth'})};$('#code-toggle').onclick=()=>{$('#code-field').hidden=!$('#code-field').hidden;if(!$('#code-field').hidden)$('#code').focus();else{$('#code').value='';render()}};
$('#favorite-filter').onclick=()=>{onlyFavorites=!onlyFavorites;$('#favorite-filter').classList.toggle('active',onlyFavorites);render()};$('#reset-search').onclick=()=>{$('#search-form').reset();onlyFavorites=false;$('#favorite-filter').classList.remove('active');document.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('active',x.dataset.category===''));render()};
function initMap(){if(!window.L){$('#map-error').hidden=false;return}try{map=L.map('map',{scrollWheelZoom:false}).setView([-12.134,-38.415],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).addTo(map);markers=L.layerGroup().addTo(map);updateMarkers(filtered())}catch{$('#map-error').hidden=false}}
function updateMarkers(list){if(!markers)return;markers.clearLayers();list.forEach(p=>L.marker([p.lat,p.lng],{icon:L.divIcon({className:'',html:`<span class="map-price">${p.price>=1000?'R$ '+(p.price/1000).toLocaleString('pt-BR')+' mil':money(p.price)}</span>`,iconSize:[85,32]})}).addTo(markers).bindPopup(`<img src="${p.image}" alt="Foto ilustrativa"><strong>${p.title}</strong><br>${money(p.price)}<br><small>Localização demonstrativa</small><a href="#imovel/${p.id}">Ver imóvel ↗</a>`))}
function renderDetail(p,scroll=true){currentProperty=p;$('#home').hidden=true;$('#detail').hidden=false;const imgs=photos(p);$('#detail').innerHTML=`<a class="back-link" href="#imoveis">← Voltar para os imóveis</a><p class="demo-note">IMÓVEL DEMONSTRATIVO · Fotos e informações ilustrativas, sem oferta comercial.</p><div class="detail-gallery"><button class="main-photo" data-photo="0"><img src="${imgs[0]}" alt="Foto principal ilustrativa de ${p.title}"><span class="photo-expand">⛶ Abrir galeria</span></button><button data-photo="1"><img src="${imgs[1]}" alt="Referência ilustrativa de arquitetura"></button><button data-photo="2"><img src="${imgs[2]}" alt="Referência ilustrativa complementar"></button></div><div class="detail-layout"><div><p class="eyebrow blue">${p.type.toUpperCase()} · ${p.id} · ${p.purpose.toUpperCase()}</p><h1>${p.title}</h1><p>⌖ ${p.district} — Alagoinhas/BA · Endereço aproximado demonstrativo</p><div class="detail-amenities"><span>${p.beds} quartos</span><span>${p.suites} suítes</span><span>${p.baths} banheiros</span><span>${p.parking} vagas</span><span>${p.area} m²</span></div><h3>Um espaço para o seu próximo capítulo</h3><p>${p.description}</p><h3>Características</h3><div class="detail-amenities">${p.features.map(f=>`<span>✓ ${f}</span>`).join('')}</div><button class="btn outline" id="detail-fav" style="margin-top:25px">${favorites.includes(p.id)?'♥ Remover dos favoritos':'♡ Salvar nos favoritos'}</button><h3>Localização</h3><p>Bairro ${p.district}, Alagoinhas – BA. O endereço exato deve ser confirmado com André.</p><a class="text-link" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.district+' Alagoinhas BA')}">Explorar a região no Google Maps ↗</a></div><aside class="visit-box"><small>Valor demonstrativo${p.purpose==='Alugar'?' mensal':''}</small><strong>${money(p.price)}</strong><label>Data desejada para a visita<input type="date" id="visit-date" min="${new Date().toISOString().slice(0,10)}"></label><button class="btn primary" id="visit">Agendar uma visita ↗</button><a class="btn outline" href="${wa('Olá André, vi este imóvel no site e gostaria de mais informações. '+p.id+' — '+p.title+' (imóvel demonstrativo).')}" target="_blank" rel="noopener">Falar pelo WhatsApp ↗</a><small>A visita será solicitada pelo WhatsApp e estará sujeita à confirmação. Nenhum horário é reservado automaticamente.</small></aside></div>`;document.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>openGallery(+b.dataset.photo));$('#detail-fav').onclick=()=>toggleFavorite(p.id);$('#visit').onclick=()=>{const date=$('#visit-date').value;window.open(wa(`Olá André, gostaria de agendar uma visita. Vi o exemplo ${p.id} — ${p.title} no site e quero conhecer opções semelhantes disponíveis.${date?' Minha data preferida é '+date.split('-').reverse().join('/')+'.':''}`),'_blank','noopener')};document.title=p.title+' | André Nascimento Imóveis';if(scroll)window.scrollTo(0,0)}
function route(){const match=location.hash.match(/^#imovel\/(AN\d+)$/);if(match){const p=properties.find(p=>p.id===match[1]);if(p){renderDetail(p);return}}const wasDetail=!$('#detail').hidden;currentProperty=null;$('#detail').hidden=true;$('#home').hidden=false;document.title='André Nascimento Imóveis | Seu próximo capítulo';if(wasDetail){setTimeout(()=>{const target=document.getElementById((location.hash||'#inicio').slice(1));if(target)target.scrollIntoView();map?.invalidateSize()},50)}$('header').classList.remove('menu-open')}
window.addEventListener('hashchange',route);function openGallery(index){galleryIndex=index;updateGallery();$('#fullscreen').showModal()}function updateGallery(){const imgs=photos(currentProperty);$('#fullscreen img').src=imgs[galleryIndex];$('#gallery-counter').textContent=(galleryIndex+1)+' / '+imgs.length+' · Fotografias ilustrativas'}$('.close-gallery').onclick=()=>$('#fullscreen').close();$('.gallery-prev').onclick=()=>{galleryIndex=(galleryIndex+2)%3;updateGallery()};$('.gallery-next').onclick=()=>{galleryIndex=(galleryIndex+1)%3;updateGallery()};$('#fullscreen').addEventListener('keydown',e=>{if(e.key==='ArrowLeft')$('.gallery-prev').click();if(e.key==='ArrowRight')$('.gallery-next').click()});
$('#sell-form').onsubmit=e=>{e.preventDefault();const form=e.target;if(!form.reportValidity())return;const d=new FormData(form);window.open(wa(`Olá André, quero vender meu imóvel.\nNome: ${d.get('name')}\nWhatsApp: ${d.get('phone')}\nTipo: ${d.get('type')}\nBairro: ${d.get('district')}`),'_blank','noopener')};
function toggleChat(open){$('#chat').hidden=!open;$('#chat-toggle').setAttribute('aria-expanded',String(open))}$('#chat-toggle').onclick=()=>toggleChat($('#chat').hidden);$('#close-chat').onclick=()=>toggleChat(false);document.addEventListener('keydown',e=>{if(e.key==='Escape')toggleChat(false)});window.slideReviews=dir=>$('#review-slider').scrollBy({left:dir*($('#review-slider').firstElementChild.offsetWidth+23),behavior:'smooth'});
let ticking=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;window.addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{const y=window.scrollY;$('header').classList.toggle('scrolled',y>20);if(!reduced&&innerWidth>700&&y<850&&!$('#home').hidden){$('.hero-photo').style.transform=`scale(${1+Math.min(y/3500,.16)}) translateY(${y*.12}px)`;$('.hero-content').style.transform=`translateY(${-y*.14}px)`}ticking=false})},{passive:true});
render();route();initMap();if(!reduced&&'IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.section-top,.trust-heading,.broker>div,.sell>div').forEach(el=>{el.classList.add('reveal');observer.observe(el)})}

if(!reduced&&'IntersectionObserver' in window){const stat=$('.stats>div:nth-child(2) strong');const counter=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){let start;function frame(time){if(!start)start=time;const t=Math.min((time-start)/900,1);stat.textContent='+'+Math.round(120*(1-Math.pow(1-t,3)));if(t<1)requestAnimationFrame(frame);counter.disconnect()}},{threshold:.5});counter.observe(stat)}
